### ISSUE TITLE
schemas inconsistencies

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator#204]
Only `Impression` should have `publisher` field, the current restriction is non existent:
`publisher: Joi.string(),`

adUnit is also defined with no restrictions, which will apply to all types, please make a list of the types that should include it.

For now I have this as a strictly defined types:

1. IMPRESSION:
- publisher
- adUnit,
2. UPDATE_IMPRESSION_PRICE:
- price
3. IMPRESSION_WITH_COMMISSION:
// as discussed with Ivo, we still rename the `address` to `publisher` for backwards compatibility
- earners: [Earner { address, promilles}],
4. PAY:
- outputs: {String: BigNum},
5. PAUSE_CHANNEL:
--
6. CLOSE:
--

@samparsky  Please check those, give me an update if any fields are missing or are in places where there shouldn't be + this should be reflected in the `schams.js`

**Comment by samparsky** [comment]
For proper documentation.
Some events are creator only events i.e. they can be only sent by the creator of the channel 
CLOSE, PAY, UPDATE_IMPRESSION_PRICE, PAUSE_CHANNEL

1. IMPRESSION
```js
{
type: "",
publisher: "",
adUnit: ""
}
```

2. UPDATE_IMPRESSION_PRICE
```
{
type:
price: 
}
```

3 IMPRESSION_WITH _COMMISSION
```
{
type: "IMPRESSION_WITH _COMMISSION",
earners: [{ address, promilles}]
}
```
4: PAY
```
{
type: PAY
outputs: {publisher: '10', publisher: '11' }
}
```
5: PAUSE_CHANNEL
```
{
type: "PAUSE_CHANNEL"
}
```
6: CLOSE
```
{
type: "CLOSE"
}
```
