### ISSUE TITLE
add DNT policy to the docker image

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-validator#209]
add `.well-known/dnt-policy.txt` (see https://www.eff.org/dnt-policy) and ensure any logs are not retained more than 10 days

re logs: currently we have no nginx config in the repo

**Comment by shteryana** [comment]
DNT policy added to ~^(tom|jerry)\.(adex|moonicorn)\.network - 

https://tom.adex.network/.well-known/dnt-policy.txt
https://jerry.adex.network/.well-known/dnt-policy.txt

Nginx config is here - https://github.com/AdExNetwork/adex-validator/blob/master/nginx.conf
(note: no logging at all takes place if DNT header is present/set)
