### ISSUE TITLE
/analytics: by year requests are returning incorrect time groups

### ISSUE THREAD

**Issue by IvoPaunov** [AdExNetwork/adex-validator#310]
Analytics for year period are grouped by ROUGH_MONTH span that has issue with matching actual  start of months because of leap years. We can use `mongo` aggregations to get the correct start of the months as time groups.

**Comment by samparsky** [comment]
This will make the query quite complex

**Comment by IvoPaunov** [comment]
It's already done. I'll make PR soon,  just need to test it more with the analytics charts on the platform.

**Comment by samparsky** [comment]
How is the testing going? Does that fix the issue now?

**Comment by IvoPaunov** [comment]
It's ready. There are just UI touches left.
