### ISSUE TITLE
flagging channels as exhausted does not work in prod

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-validator#332]
The validators in production never properly flag channels as exhausted: on https://tom.adex.network/channel/list, the exhausted channels have exhausted set to `[true]` instead of `[true,true]`

Same on jerry

Market bug - out of scope for this repo but please look at it while investigating and fix it - check out market.adex.network/campaigns - the market seems to keep `exhausted: []` for all campaigns; the market does not care about this property so it shouldn't sync it all - as the market figures out by itself whether a campaign is exhausted and it should be that way

related #307

**Comment by samparsky** [comment]
@Ivshti this has been resolved right?

**Comment by Ivshti** [comment]
@rori4 can help with that, I think he’ll check it

**Comment by rori4** [comment]
let me check I forgot about it

**Comment by rori4** [comment]
I am not sure it is fixed. I have checked some campaigns that have been completed recently in the adex account and campaign 
0x30ead09eef4d922fcfef29c3a8c6e5ea7597b9ab4ee24d543cb8d115f63effc0 has completed and was with 2000DAI budget but in the timeframe analytics the total spent is ~2018.47

Also campaign 0xc408edcdd3a88655245c4bdc07653dc3046208d79dc131109c3ad0829fab0aea has completed and had a budget of 1500DAI but in the timeframe analytics it shows ~1513.90

Btw when was this fixed and where is the PR? I can't find it.

**Comment by Ivshti** [comment]
@rori4 ask @samparsky, it was fixed in the Rust repo. It was fixed in this repo even further back in time, in https://github.com/AdExNetwork/adex-validator/commit/00de14d29df6a5717498e5e2252e905aedacb48d

the campaign you're talking about only has the 0th property exhausted set to true: https://tom.adex.network/channel/0xc408edcdd3a88655245c4bdc07653dc3046208d79dc131109c3ad0829fab0aea/status (in jerry also https://jerry.adex.network/channel/0xc408edcdd3a88655245c4bdc07653dc3046208d79dc131109c3ad0829fab0aea/status) 

So it appears this bug is still present 

@samparsky any clue why?

**Comment by Ivshti** [comment]
Going forward this should be solved for all new campaigns

In any case it's not, the problem is most likely a race condition of some kind
