### ISSUE TITLE
Advanced analytics with epoch key are incorrect

### ISSUE THREAD

**Issue by IvoPaunov** [AdExNetwork/adex-validator#335]
We are using 
https://github.com/AdExNetwork/adex-validator/blob/903a703f7de5ccd973e2372bb5af9d63c03defcd/services/sentry/analyticsRecorder.js#L8
for the analytics keys and assuming we have the data for the past \~30 days but this no how it works. It returns the data since last epoch which is 0\~30 days. 

There are some possible solutions:
- keep the records as they are and return aggregated data since the beginning (merge all epoch records)
- start over and keep record for each day - return them merged for the past 30 day and expire the old keys
- keep the records as they are and  return all not merged by epoch - then display the data on the UI by epoch - it will be ugly because for the current days timeframes will be like 18.01.21-17.02.21 etc. (same problem as https://github.com/AdExNetwork/adex-validator/issues/310) with the leap years
- some REDIS magic?

**Comment by Ivshti** [comment]
I think the third one is the cleanest because it's the most correct and relatively easy

**Comment by Ivshti** [comment]
Going to close this since this is an UI issue I think
